### PR TITLE
optimization: Transpose in Linear::new

### PR DESCRIPTION
**Pull request by Huguet57**
Would this help with Issue #96 (the first sub-issue)?

### CODE REVIEW

**Comment by Huguet57** [comment]
This is the result using `w_t`:

```
running 1 test
Token: [50363]
Token: [50257]
Decoded: 
```

Has this something to do with Rust's borrow checker or something?

**Comment by Huguet57** [comment]
Just checked that it indeed has something to do with permute() being a lazy operation. Not sure if it's worth to keep rowing in this direction or try another approach

**Comment by FL33TW00D** [comment]
Hi @Huguet57,
Thanks for looking into this.

Yeah it's a problem of the lazy operation.
The best approach is to add support for transposed matrix muliplications. This does the transpose whilst doing the matmul, and all is well.

We will have an api like:
```rust
let args = MatMulArgs {
    trans_b: true,
};
let y = input.matmul(&self.w, rags)?;
```

**Comment by Huguet57** [comment]
I see, interesting

**Pull request closed without merging**
