### PR TITLE
Instructions for running the tests

### PR DESCRIPTION
**Pull request by Huguet57**
Might help for people uninitiated with pyenv or Rust.

### CODE REVIEW

**Comment by Huguet57** [comment]
As discussed in Issue https://github.com/FL33TW00D/ratchet/issues/85

**Comment by FL33TW00D** [comment]
@Huguet57 Please rebase, I fixed CI :)

**Comment by Huguet57** [comment]
I think I did 👀

**Comment by FL33TW00D** [comment]
@Huguet57 Thank you!

**Pull request merged**
